2024-coding-test-study/2024-2

- week01/AC/김지연.py
- week01/여행 계획/김지연.py
- week01/좋은 단어/김지연.py
- Problem: [AC](https://www.acmicpc.net/problem/5430)
- Issue: [#2 ]()
- 시도 횟수:
- 풀이 시간:
문제에서 요구하는대로 'R'이면 .reverse() 내장 함수 사용해서 함수 수행하고, 'D'이면 popleft()로 첫번째 요소 제거하면 된다고 생각함.
reverse()의 시간복잡도가 O(n)이므로 테스트 케이스와 각 테스트 케이스에서 수행할 함수가 최대일 경우 1억번의 연산을 하게 되는데 여기에 reverse가 중첩되므로 1억을 넘어가서 시간초과.
해결방법은 배열을 진짜로 뒤집는 거 대신 pop() (O(1))을 수행하면 된다. toggle이라는 변수를 사용해서 'R'함수 이면 toggle을 변경해서 toggle값에 따라 pop(), popleft() 로 배열의 앞뒤를 번걸아가며 연산 수행하면 된다.
deque를 사용해서 덱 구현. 
- `O(n^2)`
---
- Problem: [좋은단어](https://www.acmicpc.net/problem/3986)
- Issue: [#2 ]()
- 시도 횟수:
- 풀이 시간:
스택 자료구조를 사용해야된다는 걸 알고 푸니까 쉽게 풀리긴함. 근데 문제 이해하는데 어려움이 있었음. 백준 질문 게시판보고 문제 이해했다.
문제 이해 도움 글: https://www.acmicpc.net/board/view/137654
스택을 사용해서 단어를 하나씩 꺼내면서 현재 단어와 스택 포인터가 가리키고 있는 요소가 같으면 pop. 모든 연산이 끝난 후에 스택이 비어있어야 좋은 단어
- `O(n^2)`
---
- …
> [Weel01] jiyeon

- week01/AC/조수지.py
- week01/좋은 단어/조수지.py
- Problem: [좋은 단어](https://www.acmicpc.net/problem/3986)
- Issue: [#5 ](https://github.com/2024-coding-test-study/2024-2/issues/5)
- 시도 횟수: 1
- 풀이 시간: 16m
X
처음 생각한 대로 풀림
스택을 이용하여 문제 해결
모두 쌍을 이루면서 교차하지 않아야 하므로 단어를 리스트에 넣어 하나하나 확인
스택의 탑과 현재 문자열이 같으면 pop하고 다르다면 스택에 현재 문자열을 추가 시키는 방식으로 진행함
스택이 최종적으로 비었다면 좋은 단어의 개수를 나타내는 good에 1을 더해 최종적으로 출력해 줌
- `O(n)`
- Problem: [AC](https://www.acmicpc.net/problem/5430)
- Issue: [#5 ](https://github.com/2024-coding-test-study/2024-2/issues/5)
- 시도 횟수: 2
- 풀이 시간: 32m
첫번째 시도에서 R 함수를 실행할 때 무작정 reverse()를 작성해서 시간 초과가 났음
최대한 실행 시간을 짧아지게 하기 위해서 R 함수 여부를 체크하는 방법이 필요했음
deque를 이용하여 리스트의 양쪽에서 pop이 가능하도록 함
R 함수를 실행할 때마다 reverse()를 하는게 아니라 R 함수 여부를 판단하는 변수를 만들어 리스트의 왼쪽에서 …
> [Week01] suji

- .idea/.gitignore
- .idea/Inyro_python_algorithm_study.iml
- .idea/inspectionProfiles/profiles_settings.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- week01/AC/선지원.py
- week01/여행 계획/선지원.py
- week01/좋은 단어/선지원.py
문제
Problem: [AC](https://www.acmicpc.net/problem/5430)
Issue: [#6 ](https://github.com/2024-coding-test-study/2024-2/issues/6)
시도 횟수: 2
풀이 시간: 45분
시행착오
reverse 함수로 접근 하였으나 시간 초과 발생
최종 알고리즘 설계
정방향과 역방향을 표시하는 변수를 만들어 생성하고
마지막에 방향에 맞도록 출력하게 함
최악 수행 시간 복잡도
`O(T * (|p| + n))`
특이 사항 (Optional)
- Problem: []()
- Issue: []()
- 시도 횟수:
- 풀이 시간:
- ``
- Problem: [좋은단어](https://www.acmicpc.net/problem/3986)
- Issue: [#6  ](https://github.com/2024-coding-test-study/2024-2/issues/6)
- 시도 횟수: 1
- 풀이 시간: 10m
X
입력받은 값을 스택에 넣고 연속된 두 단어가 같으면 스택에서 pop*2를 수행함
작업이 끝나고 스택이 비었으면 1 아니면 0을 리턴하여 최종값에 더함 
- `O(N+len(word)`
- …
> [Week01] jiwon

- week01/AC/지재현.py
- week01/여행 계획/지재현.py
- week01/좋은 단어/example
- week01/좋은 단어/지재현.py
- Problem: [좋은 단어](https://www.acmicpc.net/problem/3986)
- Issue: [#4](https://github.com/2024-coding-test-study/2024-2/issues/4)
- 시도 횟수: 2
- 풀이 시간: 30m
처음에는 스택을 사용하지 않고 1차원 배열을 이용하여 A, B를 0, 1처럼 생각하여 선을 긋는 행위를 0, 1이 이어져있음을 판단하여 풀어보려고 했습니다만, 잘 구현되지 않았습니다.
역 폴란드 연산, 후위표기법(RPN)에서 스택을 사용하는 방식과 매우 유사한 문제라는 것을 깨달았습니다. 연산자를 만났을 때, 스택에 순차적으로 담아두었던 수를 2개 꺼내 연산하고
다시 스택에 넣어 연산을 반복하는 방식과 좋은 단어에서 A, B를 각각 연결하는 방식이 매우 유사했습니다.
n : 스택에 수를 넣는 시간, m : 끝의 두 수를 확인하고 꺼내는 시간
- `O(n + m)`
X
- Problem: [AC](https://www.acmicpc.net/problem/5430)
- Issue: [#4](https://github.com/2024-coding-test-study/2024-2/issues/4)
- 시도 횟수: 5
- 풀이 시간: 45분
결과는 잘 출력이 됐으나, 시간초과 문제가 계속 발생했습니다.
초반 시도에서는 덱을 쓰지않았고, 빠른 입력에 대한 고려도 하지 않았으며, 'R' 명령어에 대한 처리도 단순했습니다. 
결국에는 덱을 사용하지 않았고, 'R' 명령어를 바로 처리하지 않았으며 최종적으로 홀수, 짝수에 대해서만 플래그로 처리했습니다. …
> [Week01] jaehyun

- week02/행성터널/조수지.py
- week03/1로 만들기 2/조수지.py
- week03/최소 스패닝 트리/조수지.py
- Problem: [1로 만들기 2](https://www.acmicpc.net/problem/12852)
- Issue: []()
- 시도 횟수: 3
- 풀이 시간: 50m
첫번째 시도에서는 생각나는대로 while과 if-else문을 써서 했음. 당연히 시간초과
시행착오를 거쳐 중복되는 과정을 최대한 없애줌
일단 1을 빼주는 연산을 미리 저장해두고 그 후로 2와 3으로 나눠지는 지 확인해줬음
현재 수가 2나 3으로 나눠 떨어지고 미리 저장돼있는 값(-1 연산)보다 현재 수에서 2나 3으로 나눠떨어지는 수의 연산 +1 값이 작다면 업데이트
최종 값 출력
- ``
- Problem: [최소 스패닝 트리](https://www.acmicpc.net/problem/1197)
- Issue: []()
- 시도 횟수: 3
- 풀이 시간: 깜빡하고 측정하지 않음
최소 스패닝 트리는 사이클이 만들어지면 안되기에 이걸 어떻게 구현해야 할 지 고민을 함
bfs와 유사하게 방문 여부를 저장하는 배열을 하나 만들어 줌
힙에 시작 노드를 넣고 시작 노드와 이어져있는 노드를 확인해줬음
이미 방문한 노드와 이어져있다면 건너뛰고 아니라면 힙에 추가해 줌
간선의 가중치를 weight에 더해줌
- ``
-------------------------------------------------------------------------------------------- …
> [Week03] suji

- week03/1로 만들기 2/지재현.py
- week03/최소 스패닝 트리/지재현.py
- Problem: [1로 만들기 2](https://www.acmicpc.net/problem/12852)
- Issue: [29](https://github.com/2024-coding-test-study/2024-2/issues/27)
- 시도 횟수: 2 ~
- 풀이 시간: 1시간
1로 만들기 1을 먼저 풀어보고 시도했으나, 여러번의 시간초과가 발생함
dp를 통하여 N에 도달할 때까지 모든 정수의 1로 도달하는 연산을 기록하여 품
- `O(N + M)`
- Problem: [최소 스패닝 트리](https://www.acmicpc.net/problem/1197)
- Issue: [29](https://github.com/2024-coding-test-study/2024-2/issues/27)
- 시도 횟수: 풀지못함
- 풀이 시간: 2시간
크루스칼 알고리즘에 대해 알고있어서 이를 이용해서 해결하려고 함.
싸이클이 존재하는지에 대하여 bfs나 union과 같은 방법을 사용하는데 bfs는 메모리초과가 발생하여
union으로 풀려고 했지만, 이해하지 못함
- ``
- Problem: [행성 터널](https://www.acmicpc.net/problem/2887)
- Issue: [29](https://github.com/2024-coding-test-study/2024-2/issues/27)
- 시도 횟수: 풀지못함 
- 풀이 시간:
> week03-jaehyun

- week02/행성터널/선지원.py
- week03/1로 만들기 2/선지원.py
- week03/최소 스패닝 트리/선지원.py
- Problem: [1로 만들기 2](https://www.acmicpc.net/problem/12852)
- Issue: [27](https://github.com/2024-coding-test-study/2024-2/issues/27)
- 시도 횟수: 2
- 풀이 시간: 30분
없음
dp를 통해 n까지의 값을 구한 다음에, 부모를 찾아가며 출력
- `O(N^2)`
- Problem: [최소 스패닝 트리](https://www.acmicpc.net/problem/1197)
- Issue: [27](https://github.com/2024-coding-test-study/2024-2/issues/27)
- 시도 횟수: 
- 풀이 시간: 3시간
크루스칼 알고리즘에 대해 공부 함
union-parent 및 크루스칼 알고리즘을 통해 구현
- ``
- Problem: [행성 터널](https://www.acmicpc.net/problem/2887)
- Issue: [27](https://github.com/2024-coding-test-study/2024-2/issues/27)
- 시도 횟수: 
- 풀이 시간: 2시간
위의 최소 스패닝 트리를 이용하여, 모든 노드의 거리를 계산하여 queue에 집어 넣었으나 메모리 초과 문제 발생,
이 메모리 초과 문제를 잡지 못하여 검색 결과 x, y, z 축으로 정렬하여 인접한 노드의 거리만 계산 한다면 N^2 -> 3N 으로 시간 복잡도
및 메모리의 사용량이 감소 한다는 점을 이용하여 풀이함
union-parent 및 크루스칼 알고리즘을 통해 구현
- ``
> Week03 JiWon

- week03/최소 스패닝 트리/jun.java
- Problem: [최소 스패닝 트리](https://www.acmicpc.net/submit/1197/84780216)
- Issue: [week 03](https://github.com/2024-coding-test-study/2024-2/issues/23#issue-2567681140)
- 시도 횟수: 3번
- 풀이 시간: 1시간
현재 일반적인 그래프 이론으로 설계를 해보았더니 메모리 초과가 떠서 실패를 해보았다.
일단 자바로 설계를 해보았지만 아마 크루스칼 알고리즘으로 풀어서 메모리 초과를 맞닥드렸다.
아마 파이썬도 이런식으로 풀면 오류가 날거 같아. 인접 리스트인 크루스칼 알고리즘을 설계해서 파이썬으로 다시 풀어봐야겠다.
시행착오 기록 겸 작성해봅니다.
- ``
> [Week03] Jun

- week04/강의실배정/조수지.py
- week04/결혼식/조수지.py
- week04/이친수/조수지.py
- Problem: [이친수](https://www.acmicpc.net/problem/2193)
- Issue: [#34 ](https://github.com/2024-coding-test-study/2024-2/issues/34)
- 시도 횟수: 2
- 풀이 시간: 1h
처음에는 힙으로 하려다가 실패
n-1자리의 이친수에 0을 붙이고 n-2자리의 이친수에 01을 붙이면 n자리의 이친수가 된다는것을 깨달아 코드로 옮김
- ``
- Problem: [결혼식](https://www.acmicpc.net/problem/5567)
- Issue: [#34 ](https://github.com/2024-coding-test-study/2024-2/issues/34)
- 시도 횟수: 2
- 풀이 시간:
인접 리스트 형식으로 입력 받은 다음
상근이의 친구들을 방문하고 친구들의 친구들까지 방문하여 해결
- ``
- Problem:  [강의실 배정](https://www.acmicpc.net/problem/11000)
- Issue: [#34 ](https://github.com/2024-coding-test-study/2024-2/issues/34)
- 시도 횟수:
- 풀이 …
> [Week04] suji

- week04/강의실배정/김지연.py
- week04/결혼식/김지연.py
- week04/이친수/김지연.py
- Problem: [강의실 배정](https://www.acmicpc.net/problem/11000)
- Issue: [#33 ]()
- 시도 횟수: 3
- 풀이 시간:
강의실의 개수가 최소가 되야하므로 수업 시간이 끝나는 시간을 기준으로 우선순위 큐를 사용해서 풀이하면 된다고 생각    
우선순위 큐에 끝나는 시간 기준으로 정렬하도록 하고, 차례로 꺼내면서    
다음 수업 시간 시작 시간 >= 큐에서 꺼낸 수업 끝나는 시간 조건을 만족하면 큐에  다음 수업 시간을 넣어준다. 조건을 만족하지 않으면 이전 수업시간과, 다음 수업 시간을 우선순위큐에 넣어준다.
위 방식으로 풀면 반례가 있음.(코드 참고)    
입력 받은 강의 시간을 시작 시간 순으로 정렬하면 반례 해결 -> 시간초과남    
시간초과는 io시간 문제였음.
우선순위 큐를 사용한 그리디 문제
- `O(N)`
-----
- Problem: [결혼식](https://www.acmicpc.net/problem/5567)
- Issue: [#33 ]()
- 시도 횟수: 1
- 풀이 시간:
입력갑을 인접리스트로 저장하고 상근이와 연결된 노드 개수 + 상근이의 친구의 친구의 개수 를 하면 답이나옴. 겹치는 친구가 있을수도 있으니 visited배열을 사용해서 처음 방문한 노드를 방문할 때만 answer 수 늘리기
상근이의 친구와,  친구의 친구를 찾기 위해 완전 탐색 (n이 최대 500이라 가능)
- `O(N^2)`
-----    
- Problem: [이친수](https://www.acmicpc.net/problem/2193)
- Issue: …
> Week04 jiyeon

- week04/강의실배정/지재현.py
- week04/결혼식/지재현.py
- week04/이친수/지재현.py
- Problem: [결혼식](https://www.acmicpc.net/problem/5567)
- Issue: [#40]()
- 시도 횟수: 5
- 풀이 시간: 50분
문제를 모든 연결된 친구관계로 풀었다가 잘못풀어서 다시 문제를 제대로 읽고 친구의 친구까지만 인접리스트를 활용하여 풀었습니다.
- `O(n)`
- Problem: [이친수](https://www.acmicpc.net/problem/2193)
- Issue: [#40]()
- 시도 횟수: 12
- 풀이 시간: 1일
이친수의 개념을 잘 이용하여 dp를 잘 구현했다고 생각했는데 끊임없는 메모리 초과로 여러번 시행착오 끝에 수를 직접 저장하지않고 수의 개수만 저장하여 풀어냈습니다
- Problem: [강의실배정](https://www.acmicpc.net/problem/11000)
- Issue: [#40]()
- 시도 횟수: 12
- 풀이 시간: 1시간 20분
우선순위 큐를 먼저 구글링해서 학습하고 수업 종료시간에 맞춰 강의실을 추가해야하는지 말아야 하는지에 대한 풀이가 미흡해서 여러번의 시도 끝에 풀어냈습니다
> Week04 jaehyun

- week05/로봇청소기/조수지.py
- week05/최대힙/조수지.py
- week05/최소힙/조수지.py
- week05/트리순회/조수지.py
- week05/파일합치기3/조수지.py
- Problem: [트리 순회](https://www.acmicpc.net/problem/1991)
- Issue: [#44 ](https://github.com/2024-coding-test-study/2024-2/issues/44)
- 시도 횟수:
- 풀이 시간:
왼쪽 오른쪽으로 어떻게 진행해 나가야 할 지를 고민했다
리스트로 현재 노드, 왼쪽, 오른쪽 자식을 저장했다
각 순회법에서 인자로 받은 노드를 for문을 돌며 찾고 노드의 왼쪽 오른쪽 자식을 각각 left, right 변수에 저장한 다음
left, right에 대해서도 순회를 해준 다음 최종 출력을 해주었다
.라면 아무것도 출력하지 않는다
- ``
- Problem: [로봇 청소기](https://www.acmicpc.net/problem/14503)
- Issue: [#44 ](https://github.com/2024-coding-test-study/2024-2/issues/44)
- 시도 횟수:
- 풀이 시간:
처음에 문제를 잘못 이해해서 자꾸 틀리게 출력 되었다
(앞이 빈칸이면 무조건 직진하는 식으로 이해함...)
아무리 해도 이해가 되지 않아 구글 선생님들의 그림을 보고서야 문제를 이해했다
그 후로 구현하니까 성공..
사방 중에 빈칸이 존재한다면 90도씩 반시계 방향으로 회전한 뒤, 직진... 반복
사방을 다 청소했거나 벽인 경우, 후진
후진할 칸이 벽이면 종료 …
> [Week05] suji

- week05/로봇청소기/김지연.py
- week05/최대힙/김지연.py
- week05/최소힙/김지연.py
- week05/트리순회/김지연.py
- week05/파일합치기3/김지연.py
- Problem:  [로봇청소기](https://www.acmicpc.net/problem/14503)
- Issue: [#43 ]()
- 시도 횟수:
- 풀이 시간:
로봇 청소기의 동작원리가 반복되므로 재귀함수를 사용해서 풀면 되겠다고 생각.
방 정보가 주어지면 linked list로 정보를 저장하고 현재 위치(r,c)가 청소되어 있지 않으면 청소해주고 , 시계 반대 방향으로 회전하면서 청소가 안되어 있는 칸이 있으면 clean 함수를 호출해서 과정을 반복해주면 된다.
시계 반대 방향으로 회전하는걸 구현하기 위해서 동서남북으로 가기 위한 x, y 좌표를 구성했다.
현재 위치 x, y 에서 서쪽으로 가려면 x + 0, y -1, 남쪽은 x+1, y+0, 동쪽은 x + 0, y + 1, 북쪽은 x-1, y+0이므로 dx, dy 리스트를 따로 만들었다.
아래 코드가 현재 방향에서 시계 반대 방향으로 회전하는 코드
```python
for i in range(1, 5): #현재 방향에서 일단 90도 회전 후 한칸 전진했을 때
nx = x + dx[(idx + i) % 4] #room[nx][ny] 현재 방향에서 한칸 전진
ny = y + dy[(idx + i) % 4]
```
현재 방향을 기준으로 시계 반대방향으로 회전해야하므로 방향을 정의한 리스트(direction)를 만들고 현재 방향을 `idx = direction.index(d)`로 찾고, 현재 방향(idx)를 기준으로 dx, dy를 활용해서 시계 반대 방향으로 회전하도록 구현
여기서 로봇 청소기가 회전하면서 청소 되지 않은 칸을 찾았다면 함수를 …
> [Week05] jiyeon

- week05/로봇청소기/지재현.py
- week05/절대값힙/README.md
- week05/절대값힙/지재현.py
- week05/최대힙/지재현.py
- week05/최소힙/지재현.py
- week05/트리순회/지재현.py
- week05/파일합치기3/지재현.py
- Problem: [최대힙](https://www.acmicpc.net/problem/11279)
- Issue: [47](https://github.com/2024-coding-test-study/2024-2/issues/47)
- 시도 횟수: 1
- 풀이 시간: 5m
- Problem: [최소힙](https://www.acmicpc.net/problem/1927)
- Issue: [47](https://github.com/2024-coding-test-study/2024-2/issues/47)
- 시도 횟수: 1
- 풀이 시간: 5m
- Problem: [로봇청소기](https://www.acmicpc.net/problem/14503)
- Issue: [47](https://github.com/2024-coding-test-study/2024-2/issues/47)
- 시도 횟수: 1
- 풀이 시간: 1h
- Problem: [파일합치기3](https://www.acmicpc.net/problem/13975)
- Issue: [47](https://github.com/2024-coding-test-study/2024-2/issues/47)
- 시도 횟수: 2
- 풀이 시간: 10m
> [Week05] jaehyun

- .idea/workspace.xml
- week05/로봇청소기/선지원.py
- week05/트리순회/선지원.py
- week05/파일합치기3/선지원.py
- Problem: [트리순회](https://www.acmicpc.net/problem/1991)
- Issue: [#45 ](https://github.com/2024-coding-test-study/2024-2/issues/45)
- 시도 횟수: 1
- 풀이 시간: 10
-
재귀를 이용하여 전위, 후위, 중위 전부 똑같은 매커니즘으로 표기
- ``
---
- Problem: [로봇청소기](https://www.acmicpc.net/problem/14503)
- Issue: [#45 ](https://github.com/2024-coding-test-study/2024-2/issues/45)
- 시도 횟수: 4
- 풀이 시간: 60
-
방향을 유지한채로 뒤로 가기, 1을 벽으로 인식 등의 문제 해결을 하느라 오랜 시간이 걸림,
청소할 부분이 있는지를 먼저 확인 하는걸 제외하면 문제에 있는 코드 그대로 코드로 구현을 함
- ``
---
- Problem: [파일합치기3](https://www.acmicpc.net/problem/13975)
- Issue: [#45 ](https://github.com/2024-coding-test-study/2024-2/issues/45)
- 시도 횟수: 1
- 풀이 시간: 20
-
계속 정렬을 해가면서 합치는 알고리즘이라 생각하여 heapq를 구현함
- ``
> [Week05] jiwon

- week06/16401/조수지.py
- week06/22862/조수지.py
- week06/2961/조수지.py
- Problem: [과자 나눠주기](https://www.acmicpc.net/problem/16401)
- Issue: [#54 ](https://github.com/2024-coding-test-study/2024-2/issues/54)
- 시도 횟수:
- 풀이 시간:
처음에는 문제 예시에 갇혀서 자꾸 2, 3개로만 과자를 나누려고 하다가 엄청 긴 과자가 존재할 수도 있음을 깨닫고 다시 생각해보았다
과자의 길이는 양의 정수여야 함으로 최소 길이 1, 최대 길이 max(snack_len)으로 설정해 준 다음 이분 탐색으로 해결
- `O(n log n)`
- Problem: [도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
- Issue: [#54 ](https://github.com/2024-coding-test-study/2024-2/issues/54)
- 시도 횟수:
- 풀이 시간:
같은 개수의 재료로 요리할 때, 여러 개의 조합이 나오는 걸 어떻게 구현해야 할 지 막막했다.
파이썬에는 조합을 구해주는 외장함수가 있다는 것을 알게 되어 사용했다
- `O(n^2)`
- Problem: [가장 긴 짝수 연속한 …
> [Week06] suji

- .idea/workspace.xml
- week06/16401/선지원.py
- week06/22862/선지원.py
- week06/2961/선지원.py
- Problem: [도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
- Issue: [#53 ](https://github.com/2024-coding-test-study/2024-2/issues/53)
- 시도 횟수: 1
- 풀이 시간: 10
-
combination으로 모든 경우의 수를 뽑아서 계산
- ``
---
- Problem: [과자 나눠주기](https://www.acmicpc.net/problem/16401)
- Issue: [#53 ](https://github.com/2024-coding-test-study/2024-2/issues/53)
- 시도 횟수: 3
- 풀이 시간: 60
-
이분 탐색에 대해 잘 몰라서 이분 탐색을 공부 한 후 똑같은 로직이기 때문에 똑같이 옮김
- ``
---
- Problem: [가장 긴 짝수 연속한 부분 수열 (large)](https://www.acmicpc.net/problem/22862)
- Issue: [#53 ](https://github.com/2024-coding-test-study/2024-2/issues/53)
- 시도 횟수: 1
- 풀이 시간: 20
-
투 포인터 알고리즘에 대해 공부한 후 로직을 만들어서 계산
- ``
> [week06] jiwon

- week06/16401/김지연.py
- week06/22862/김지연.py
- week06/2961/김지연.py
- Problem: [16401](https://www.acmicpc.net/problem/16401)
- Issue: [#57 ]()
- 시도 횟수:
- 풀이 시간:
처음에는 answer에 조카에게 나눠줄 수 있는 최대 길이를 저장해둔 다음에 -1씩 줄여가면서 구해보자했다.
[해당 풀이로 푼 커밋](https://github.com/2024-coding-test-study/2024-2/tree/fe2ba7672ae7f2c5b7b5f8c79b706efcb589da5c)을 보면 해당 풀이의 문제점이 뭔지 코멘트를 달아놓았다.
문제를 보면 '과자 길이' 를 대상으로 최대 길이는 구하는 것이다. 즉, 이진 탐색의 대상이 과자 길이어야한다는 말이다.
이전에 풀었던거는 최대 과자길이는 구해놓고, 주어진 과자길이를 대상으로 이진 탐색을 했다.
최소과자길이 start = 1, 최대 과자 길이 end = lst[-1]로 하고, start 와 end를 조정하면서 mid 를 구하고 mid에 대해서 주어진 과자 길이는 조카의 수(m) 만큼 나눠줄 수 있는지 for문으로 돌리고 개수가 모자르면 길이 줄여주고, 충분히 나눠줄 수 있으면 길이를 늘려서 다시 탐색한다.
과자 막대 길이를 대상으로 한 이진 탐색
- `O(NlogN)`
----
- Problem: [2961](https://www.acmicpc.net/problem/2961)
- Issue: [#57 ]()
- 시도 횟수:
- 풀이 시간:
문제 제대로 읽지 않고 풀어서 현타옴
재료 n개를 1~n개까지 조합으로 만들고 모든 조합에 대해서 쓴맛과 신맛의 차이를 구해서 최소를 …
> [Week06] jiyeon

- week06/16401/지재현.py
- week06/2961/지재현_비트마스킹.py
- week06/2961/지재현_조합.py
- Problem: [도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
- Issue: [#59](https://github.com/2024-coding-test-study/2024-2/issues/59)
- 시도 횟수: 2
- 풀이 시간: 15m
- Problem: [과자나눠주기](https://www.acmicpc.net/problem/16401)
- Issue: [#59](https://github.com/2024-coding-test-study/2024-2/issues/59)
- 시도 횟수: 2
- 풀이 시간: 20m
- Problem: [가장 긴 짝수 증가하는 부분 수열 large](https://www.acmicpc.net/problem/22862)
- Issue: [#59](https://github.com/2024-coding-test-study/2024-2/issues/59)
- 시도 횟수: 1 ~
- 풀이 시간: 풀지못함
> week06-jaehyun

- week06/16401/jun.java
- week06/16401/jun.py
- week06/22862/jun.java
- week06/2961/jun.java
- Problem: [과자 나눠주기](https://www.acmicpc.net/problem/16401)
- Issue: [week 6](https://github.com/2024-coding-test-study/2024-2/issues/56#issue-2634393123)
- 시도 횟수: 10
- 풀이 시간: 2시간
이진 탐색에서 예외처리를 제외하고 코드를 짜서 zero division 문제가 발생하였음
그걸 처리하는데 꽤 오랜 시간이 걸림
결국 모든 길이를 mid값으로 나누어서 사람 명수가 cnt보다 작다면 mid값이 작다는 것이고 반대면 mid값이 크다는 것이다. 
- ``
- Problem: [도영이가 만든 맛있는 음식](https://www.acmicpc.net/problem/2961)
- Issue: [week 6](https://github.com/2024-coding-test-study/2024-2/issues/56#issue-2634393123)
- 시도 횟수: 5
- 풀이 시간: 2시간
비트마스킹 문제라 접근 방식을 초반에 브루트포스로 하여 경우의 수가 이상하게 돌아가는 문제가 발생
결국 해설을 보고 비트마스킹에 대해 공부를 한 후 접근을 다시 해보아도 안보여서 결국 블로그 글을 참고하였다.
결국 bit = 1<<repeat_num 즉 반복 횟수 만큼 1칸씩 shift를 진행하여 비트 경우의 수를 만들어주고 그 경우의 수들에서 if((i & (1 << j)) > 0) 결과과 1일 경우에만 경우를 따지는 방향으로 만들었더니 만들어졌다.
- ``
Problem: [문제이름](문제사이트) …
> [week 6] jun
